theme: jekyll-theme-time-machine
title: Mark Albrand
descrpition: I'm a student, with a great desire of learning new things. I'm liking a lot careers related to CyberSecurity. I'm learning mainly Python and C.